// ===== ARABICDATA.JS - Complete Data File =====
// 300+ Words, 200+ Phrases, 30+ Khutbah Words, 20+ Dhikr Slides

// ========== 300+ QUR'ANIC WORDS ==========
const arabicWords = [
    // Pronouns & Particles (50)
    { arabic: "هو", translit: "Huwa", meaning: "he", type: "pronoun", tajweed: "soft h" },
    { arabic: "هم", translit: "Hum", meaning: "they (m)", type: "pronoun", tajweed: "" },
    { arabic: "هن", translit: "Hunna", meaning: "they (f)", type: "pronoun", tajweed: "" },
    { arabic: "أنا", translit: "Ana", meaning: "I", type: "pronoun", tajweed: "" },
    { arabic: "نحن", translit: "Naḥnu", meaning: "we", type: "pronoun", tajweed: "ḥ deep" },
    { arabic: "أنت", translit: "Anta", meaning: "you (m)", type: "pronoun", tajweed: "" },
    { arabic: "أنت", translit: "Anti", meaning: "you (f)", type: "pronoun", tajweed: "" },
    { arabic: "أنتم", translit: "Antum", meaning: "you all (m)", type: "pronoun", tajweed: "" },
    { arabic: "أنتن", translit: "Antunna", meaning: "you all (f)", type: "pronoun", tajweed: "" },
    { arabic: "الذي", translit: "Alladhī", meaning: "the one who (m)", type: "pronoun", tajweed: "dh soft" },
    { arabic: "التي", translit: "Allatī", meaning: "the one who (f)", type: "pronoun", tajweed: "" },
    { arabic: "الذين", translit: "Alladhīna", meaning: "those who (m)", type: "pronoun", tajweed: "" },
    { arabic: "اللاتي", translit: "Allātī", meaning: "those who (f)", type: "pronoun", tajweed: "" },
    { arabic: "اللائي", translit: "Allā'ī", meaning: "those who (f)", type: "pronoun", tajweed: "" },
    { arabic: "ما", translit: "Mā", meaning: "what / not", type: "particle", tajweed: "" },
    { arabic: "من", translit: "Man", meaning: "who", type: "particle", tajweed: "" },
    { arabic: "من", translit: "Min", meaning: "from", type: "preposition", tajweed: "" },
    { arabic: "إلى", translit: "Ilā", meaning: "to", type: "preposition", tajweed: "" },
    { arabic: "على", translit: "'Alā", meaning: "on", type: "preposition", tajweed: "‘ayn deep" },
    { arabic: "في", translit: "Fī", meaning: "in", type: "preposition", tajweed: "" },
    { arabic: "عن", translit: "'An", meaning: "from / about", type: "preposition", tajweed: "‘ayn" },
    { arabic: "مع", translit: "Ma'a", meaning: "with", type: "preposition", tajweed: "‘ayn" },
    { arabic: "ب", translit: "Bi", meaning: "with / by", type: "preposition", tajweed: "" },
    { arabic: "ل", translit: "Li", meaning: "for / to", type: "preposition", tajweed: "" },
    { arabic: "ك", translit: "Ka", meaning: "like", type: "preposition", tajweed: "" },
    { arabic: "و", translit: "Wa", meaning: "and", type: "conjunction", tajweed: "" },
    { arabic: "ف", translit: "Fa", meaning: "then / so", type: "conjunction", tajweed: "" },
    { arabic: "ثم", translit: "Thumma", meaning: "then", type: "conjunction", tajweed: "th soft" },
    { arabic: "حتى", translit: "Ḥattā", meaning: "until", type: "preposition", tajweed: "ḥ deep" },
    { arabic: "عند", translit: "'Inda", meaning: "with / near", type: "preposition", tajweed: "‘ayn" },
    { arabic: "قبل", translit: "Qabla", meaning: "before", type: "adverb", tajweed: "q deep" },
    { arabic: "بعد", translit: "Ba'da", meaning: "after", type: "adverb", tajweed: "‘ayn" },
    { arabic: "فوق", translit: "Fawqa", meaning: "above", type: "adverb", tajweed: "q deep" },
    { arabic: "تحت", translit: "Taḥta", meaning: "under", type: "adverb", tajweed: "ḥ deep" },
    { arabic: "بين", translit: "Bayna", meaning: "between", type: "adverb", tajweed: "" },
    { arabic: "حول", translit: "Ḥawla", meaning: "around", type: "adverb", tajweed: "ḥ" },
    { arabic: "خلف", translit: "Khalfa", meaning: "behind", type: "adverb", tajweed: "kh deep" },
    { arabic: "أمام", translit: "Amāma", meaning: "in front", type: "adverb", tajweed: "" },
    { arabic: "يمين", translit: "Yamīn", meaning: "right side", type: "adverb", tajweed: "" },
    { arabic: "شمال", translit: "Shimāl", meaning: "left side", type: "adverb", tajweed: "" },
    { arabic: "ذلك", translit: "Dhālika", meaning: "that", type: "demonstrative", tajweed: "dh" },
    { arabic: "هذا", translit: "Hādhā", meaning: "this", type: "demonstrative", tajweed: "dh" },
    { arabic: "هذه", translit: "Hādhihi", meaning: "this (f)", type: "demonstrative", tajweed: "dh" },
    { arabic: "هؤلاء", translit: "Hā'ulā'i", meaning: "these", type: "demonstrative", tajweed: "" },
    { arabic: "تلك", translit: "Tilka", meaning: "that (f)", type: "demonstrative", tajweed: "" },
    { arabic: "كل", translit: "Kull", meaning: "every / all", type: "noun", tajweed: "" },
    { arabic: "بعض", translit: "Ba'ḍ", meaning: "some", type: "noun", tajweed: "‘ayn, ḍād" },
    { arabic: "أي", translit: "Ayy", meaning: "which", type: "interrogative", tajweed: "" },
    { arabic: "كيف", translit: "Kayfa", meaning: "how", type: "interrogative", tajweed: "" },
    { arabic: "أين", translit: "Ayna", meaning: "where", type: "interrogative", tajweed: "" },
    { arabic: "متى", translit: "Matā", meaning: "when", type: "interrogative", tajweed: "" },
    { arabic: "لماذا", translit: "Limādhā", meaning: "why", type: "interrogative", tajweed: "" },
    { arabic: "كم", translit: "Kam", meaning: "how many", type: "interrogative", tajweed: "" },
    { arabic: "نعم", translit: "Na'am", meaning: "yes", type: "particle", tajweed: "‘ayn" },
    { arabic: "لا", translit: "Lā", meaning: "no / not", type: "particle", tajweed: "" },
    { arabic: "بلى", translit: "Balā", meaning: "yes (contradiction)", type: "particle", tajweed: "" },
    
    // Verbs (150)
    { arabic: "كان", translit: "Kāna", meaning: "he was", type: "verb", tajweed: "" },
    { arabic: "قال", translit: "Qāla", meaning: "he said", type: "verb", tajweed: "q deep" },
    { arabic: "آمن", translit: "Āmana", meaning: "he believed", type: "verb", tajweed: "" },
    { arabic: "كفر", translit: "Kafara", meaning: "he disbelieved", type: "verb", tajweed: "" },
    { arabic: "علم", translit: "'Alima", meaning: "he knew", type: "verb", tajweed: "‘ayn" },
    { arabic: "عمل", translit: "'Amila", meaning: "he did / worked", type: "verb", tajweed: "‘ayn" },
    { arabic: "جعل", translit: "Ja'ala", meaning: "he made", type: "verb", tajweed: "‘ayn" },
    { arabic: "أتى", translit: "Atā", meaning: "he came", type: "verb", tajweed: "" },
    { arabic: "جاء", translit: "Jā'a", meaning: "he came", type: "verb", tajweed: "" },
    { arabic: "رأى", translit: "Ra'ā", meaning: "he saw", type: "verb", tajweed: "" },
    { arabic: "سمع", translit: "Sami'a", meaning: "he heard", type: "verb", tajweed: "‘ayn" },
    { arabic: "شاء", translit: "Shā'a", meaning: "he willed", type: "verb", tajweed: "" },
    { arabic: "أراد", translit: "Arāda", meaning: "he wanted", type: "verb", tajweed: "" },
    { arabic: "قدر", translit: "Qadara", meaning: "he decreed", type: "verb", tajweed: "q deep" },
    { arabic: "خلق", translit: "Khalaqa", meaning: "he created", type: "verb", tajweed: "kh, q" },
    { arabic: "بعث", translit: "Ba'atha", meaning: "he raised / sent", type: "verb", tajweed: "‘ayn, th" },
    { arabic: "نزل", translit: "Nazzala", meaning: "he sent down", type: "verb", tajweed: "" },
    { arabic: "أنزل", translit: "Anzala", meaning: "he revealed", type: "verb", tajweed: "" },
    { arabic: "ذكر", translit: "Dhakara", meaning: "he remembered", type: "verb", tajweed: "dh" },
    { arabic: "شكر", translit: "Shakara", meaning: "he thanked", type: "verb", tajweed: "" },
    { arabic: "صبر", translit: "Ṣabara", meaning: "he was patient", type: "verb", tajweed: "ṣ heavy" },
    { arabic: "ظلم", translit: "Ẓalama", meaning: "he wronged", type: "verb", tajweed: "ẓ heavy" },
    { arabic: "هدى", translit: "Hadā", meaning: "he guided", type: "verb", tajweed: "" },
    { arabic: "ضل", translit: "Ḍalla", meaning: "he went astray", type: "verb", tajweed: "ḍ heavy" },
    { arabic: "تاب", translit: "Tāba", meaning: "he repented", type: "verb", tajweed: "" },
    { arabic: "غفر", translit: "Ghafara", meaning: "he forgave", type: "verb", tajweed: "gh" },
    { arabic: "رحم", translit: "Raḥima", meaning: "he had mercy", type: "verb", tajweed: "ḥ deep" },
    { arabic: "كتب", translit: "Kataba", meaning: "he wrote", type: "verb", tajweed: "" },
    { arabic: "قرأ", translit: "Qara'a", meaning: "he read", type: "verb", tajweed: "q deep" },
    { arabic: "تلا", translit: "Talā", meaning: "he recited", type: "verb", tajweed: "" },
    { arabic: "آتى", translit: "Ātā", meaning: "he gave", type: "verb", tajweed: "" },
    { arabic: "أكل", translit: "Akala", meaning: "he ate", type: "verb", tajweed: "" },
    { arabic: "شرب", translit: "Shariba", meaning: "he drank", type: "verb", tajweed: "" },
    { arabic: "نام", translit: "Nāma", meaning: "he slept", type: "verb", tajweed: "" },
    { arabic: "قام", translit: "Qāma", meaning: "he stood", type: "verb", tajweed: "q deep" },
    { arabic: "جلس", translit: "Jalasa", meaning: "he sat", type: "verb", tajweed: "" },
    { arabic: "دخل", translit: "Dakhala", meaning: "he entered", type: "verb", tajweed: "kh" },
    { arabic: "خرج", translit: "Kharaja", meaning: "he left", type: "verb", tajweed: "kh" },
    { arabic: "رجع", translit: "Raja'a", meaning: "he returned", type: "verb", tajweed: "‘ayn" },
    { arabic: "ذهب", translit: "Dhahaba", meaning: "he went", type: "verb", tajweed: "dh" },
    { arabic: "أخذ", translit: "Akhadha", meaning: "he took", type: "verb", tajweed: "kh, dh" },
    { arabic: "أعطى", translit: "A'ṭā", meaning: "he gave", type: "verb", tajweed: "‘ayn, ṭ" },
    { arabic: "منع", translit: "Mana'a", meaning: "he prevented", type: "verb", tajweed: "‘ayn" },
    { arabic: "نصر", translit: "Naṣara", meaning: "he helped", type: "verb", tajweed: "ṣ" },
    { arabic: "هزم", translit: "Hazama", meaning: "he defeated", type: "verb", tajweed: "" },
    { arabic: "قتل", translit: "Qatala", meaning: "he killed", type: "verb", tajweed: "q" },
    { arabic: "أحيا", translit: "Aḥyā", meaning: "he gave life", type: "verb", tajweed: "ḥ" },
    { arabic: "أمات", translit: "Amāta", meaning: "he caused death", type: "verb", tajweed: "" },
    { arabic: "سجد", translit: "Sajada", meaning: "he prostrated", type: "verb", tajweed: "" },
    { arabic: "ركع", translit: "Raka'a", meaning: "he bowed", type: "verb", tajweed: "‘ayn" },
    { arabic: "صلى", translit: "Ṣallā", meaning: "he prayed", type: "verb", tajweed: "ṣ" },
    { arabic: "صام", translit: "Ṣāma", meaning: "he fasted", type: "verb", tajweed: "ṣ" },
    { arabic: "حج", translit: "Ḥajja", meaning: "he pilgrimaged", type: "verb", tajweed: "ḥ" },
    { arabic: "عمر", translit: "'Amara", meaning: "he visited / inhabited", type: "verb", tajweed: "‘ayn" },
    { arabic: "زكى", translit: "Zakkā", meaning: "he purified", type: "verb", tajweed: "" },
    { arabic: "أنفق", translit: "Anfaqa", meaning: "he spent", type: "verb", tajweed: "q" },
    { arabic: "أطعم", translit: "Aṭ'ama", meaning: "he fed", type: "verb", tajweed: "ṭ, ‘ayn" },
    { arabic: "سقى", translit: "Saqā", meaning: "he gave drink", type: "verb", tajweed: "q" },
    { arabic: "نفع", translit: "Nafa'a", meaning: "he benefited", type: "verb", tajweed: "‘ayn" },
    { arabic: "ضر", translit: "Ḍarra", meaning: "he harmed", type: "verb", tajweed: "ḍ" },
    { arabic: "وعد", translit: "Wa'ada", meaning: "he promised", type: "verb", tajweed: "‘ayn" },
    { arabic: "أخلف", translit: "Akhlafa", meaning: "he broke promise", type: "verb", tajweed: "kh" },
    { arabic: "صدق", translit: "Ṣaddaqa", meaning: "he believed", type: "verb", tajweed: "ṣ, q" },
    { arabic: "كذب", translit: "Kadhdhaba", meaning: "he denied", type: "verb", tajweed: "dh" },
    { arabic: "فكر", translit: "Fakkara", meaning: "he thought", type: "verb", tajweed: "" },
    { arabic: "تدبر", translit: "Tadabbara", meaning: "he reflected", type: "verb", tajweed: "" },
    { arabic: "عقل", translit: "'Aqala", meaning: "he understood", type: "verb", tajweed: "‘ayn, q" },
    { arabic: "فقه", translit: "Faqiha", meaning: "he comprehended", type: "verb", tajweed: "q" },
    { arabic: "حفظ", translit: "Ḥafiẓa", meaning: "he preserved", type: "verb", tajweed: "ḥ, ẓ" },
    { arabic: "نسي", translit: "Nasiya", meaning: "he forgot", type: "verb", tajweed: "" },
    { arabic: "أحصى", translit: "Aḥṣā", meaning: "he counted", type: "verb", tajweed: "ḥ, ṣ" },
    { arabic: "حكم", translit: "Ḥakama", meaning: "he judged", type: "verb", tajweed: "ḥ" },
    { arabic: "فصل", translit: "Faṣṣala", meaning: "he detailed", type: "verb", tajweed: "ṣ" },
    { arabic: "بين", translit: "Bayyana", meaning: "he explained", type: "verb", tajweed: "" },
    { arabic: "ولى", translit: "Wallā", meaning: "he turned", type: "verb", tajweed: "" },
    { arabic: "أقبل", translit: "Aqbala", meaning: "he approached", type: "verb", tajweed: "q" },
    { arabic: "أدبر", translit: "Adbara", meaning: "he turned away", type: "verb", tajweed: "" },
    { arabic: "نادى", translit: "Nādā", meaning: "he called", type: "verb", tajweed: "" },
    { arabic: "أجاب", translit: "Ajāba", meaning: "he answered", type: "verb", tajweed: "" },
    { arabic: "دعا", translit: "Da'ā", meaning: "he supplicated", type: "verb", tajweed: "‘ayn" },
    { arabic: "استغفر", translit: "Istaghrara", meaning: "he sought forgiveness", type: "verb", tajweed: "gh" },
    { arabic: "استعان", translit: "Ista'āna", meaning: "he sought help", type: "verb", tajweed: "‘ayn" },
    { arabic: "استقام", translit: "Istaqāma", meaning: "he remained upright", type: "verb", tajweed: "q" },
    { arabic: "اهتدى", translit: "Ihtadā", meaning: "he was guided", type: "verb", tajweed: "" },
    { arabic: "ارتد", translit: "Irtadda", meaning: "he apostatized", type: "verb", tajweed: "" },
    { arabic: "أناب", translit: "Anāba", meaning: "he turned (to Allah)", type: "verb", tajweed: "" },
    { arabic: "خاف", translit: "Khāfa", meaning: "he feared", type: "verb", tajweed: "kh" },
    { arabic: "رجا", translit: "Rajā", meaning: "he hoped", type: "verb", tajweed: "" },
    { arabic: "توكل", translit: "Tawakkala", meaning: "he relied", type: "verb", tajweed: "" },
    { arabic: "عبد", translit: "'Abada", meaning: "he worshipped", type: "verb", tajweed: "‘ayn" },
    { arabic: "أشرك", translit: "Ashraka", meaning: "he associated partners", type: "verb", tajweed: "" },
    { arabic: "وحد", translit: "Waḥḥada", meaning: "he declared oneness", type: "verb", tajweed: "ḥ" },
    { arabic: "كبر", translit: "Kabbara", meaning: "he magnified", type: "verb", tajweed: "" },
    { arabic: "سبح", translit: "Sabbaḥa", meaning: "he glorified", type: "verb", tajweed: "ḥ" },
    { arabic: "هلل", translit: "Hallala", meaning: "he said La ilaha illa Allah", type: "verb", tajweed: "" },
    { arabic: "حمد", translit: "Ḥamida", meaning: "he praised", type: "verb", tajweed: "ḥ" },
    
    // Nouns (100)
    { arabic: "الله", translit: "Allāh", meaning: "Allah", type: "noun", tajweed: "glottal stop" },
    { arabic: "رب", translit: "Rabb", meaning: "Lord", type: "noun", tajweed: "" },
    { arabic: "إله", translit: "Ilāh", meaning: "god", type: "noun", tajweed: "" },
    { arabic: "عبد", translit: "'Abd", meaning: "servant", type: "noun", tajweed: "‘ayn" },
    { arabic: "رسول", translit: "Rasūl", meaning: "messenger", type: "noun", tajweed: "" },
    { arabic: "نبي", translit: "Nabī", meaning: "prophet", type: "noun", tajweed: "" },
    { arabic: "كتاب", translit: "Kitāb", meaning: "book", type: "noun", tajweed: "" },
    { arabic: "قرآن", translit: "Qur'ān", meaning: "Qur'an", type: "noun", tajweed: "q" },
    { arabic: "آية", translit: "Āyah", meaning: "sign / verse", type: "noun", tajweed: "" },
    { arabic: "سورة", translit: "Sūrah", meaning: "chapter", type: "noun", tajweed: "" },
    { arabic: "يوم", translit: "Yawm", meaning: "day", type: "noun", tajweed: "" },
    { arabic: "ليلة", translit: "Laylah", meaning: "night", type: "noun", tajweed: "" },
    { arabic: "ساعة", translit: "Sā'ah", meaning: "hour", type: "noun", tajweed: "‘ayn" },
    { arabic: "وقت", translit: "Waqt", meaning: "time", type: "noun", tajweed: "q" },
    { arabic: "شهر", translit: "Shahr", meaning: "month", type: "noun", tajweed: "" },
    { arabic: "سنة", translit: "Sanah", meaning: "year", type: "noun", tajweed: "" },
    { arabic: "أرض", translit: "Arḍ", meaning: "earth", type: "noun", tajweed: "ḍ" },
    { arabic: "سماء", translit: "Samā'", meaning: "sky", type: "noun", tajweed: "" },
    { arabic: "جنة", translit: "Jannah", meaning: "paradise", type: "noun", tajweed: "" },
    { arabic: "نار", translit: "Nār", meaning: "hellfire", type: "noun", tajweed: "" },
    { arabic: "صراط", translit: "Ṣirāṭ", meaning: "path", type: "noun", tajweed: "ṣ, ṭ" },
    { arabic: "طريق", translit: "Ṭarīq", meaning: "way", type: "noun", tajweed: "ṭ, q" },
    { arabic: "باب", translit: "Bāb", meaning: "door", type: "noun", tajweed: "" },
    { arabic: "بيت", translit: "Bayt", meaning: "house", type: "noun", tajweed: "" },
    { arabic: "مسجد", translit: "Masjid", meaning: "mosque", type: "noun", tajweed: "" },
    { arabic: "مدينة", translit: "Madīnah", meaning: "city", type: "noun", tajweed: "" },
    { arabic: "قرية", translit: "Qaryah", meaning: "village", type: "noun", tajweed: "q" },
    { arabic: "جبل", translit: "Jabal", meaning: "mountain", type: "noun", tajweed: "" },
    { arabic: "بحر", translit: "Baḥr", meaning: "sea", type: "noun", tajweed: "ḥ" },
    { arabic: "نهر", translit: "Nahr", meaning: "river", type: "noun", tajweed: "" },
    { arabic: "ماء", translit: "Mā'", meaning: "water", type: "noun", tajweed: "" },
    { arabic: "نور", translit: "Nūr", meaning: "light", type: "noun", tajweed: "" },
    { arabic: "ظلمة", translit: "Ẓulmah", meaning: "darkness", type: "noun", tajweed: "ẓ" },
    { arabic: "شمس", translit: "Shams", meaning: "sun", type: "noun", tajweed: "" },
    { arabic: "قمر", translit: "Qamar", meaning: "moon", type: "noun", tajweed: "q" },
    { arabic: "نجم", translit: "Najm", meaning: "star", type: "noun", tajweed: "" },
    { arabic: "ليل", translit: "Layl", meaning: "night", type: "noun", tajweed: "" },
    { arabic: "نهار", translit: "Nahār", meaning: "day", type: "noun", tajweed: "" },
    { arabic: "دنيا", translit: "Dunyā", meaning: "world", type: "noun", tajweed: "" },
    { arabic: "آخرة", translit: "Ākhirah", meaning: "hereafter", type: "noun", tajweed: "kh" },
    { arabic: "حياة", translit: "Ḥayāh", meaning: "life", type: "noun", tajweed: "ḥ" },
    { arabic: "موت", translit: "Mawt", meaning: "death", type: "noun", tajweed: "" },
    { arabic: "روح", translit: "Rūḥ", meaning: "spirit", type: "noun", tajweed: "ḥ" },
    { arabic: "نفس", translit: "Nafs", meaning: "soul / self", type: "noun", tajweed: "" },
    { arabic: "قلب", translit: "Qalb", meaning: "heart", type: "noun", tajweed: "q" },
    { arabic: "عقل", translit: "'Aql", meaning: "intellect", type: "noun", tajweed: "‘ayn, q" },
    { arabic: "علم", translit: "'Ilm", meaning: "knowledge", type: "noun", tajweed: "‘ayn" },
    { arabic: "جهل", translit: "Jahl", meaning: "ignorance", type: "noun", tajweed: "" },
    { arabic: "حكمة", translit: "Ḥikmah", meaning: "wisdom", type: "noun", tajweed: "ḥ" },
    { arabic: "فهم", translit: "Fahm", meaning: "understanding", type: "noun", tajweed: "" },
    { arabic: "إيمان", translit: "Īmān", meaning: "faith", type: "noun", tajweed: "" },
    { arabic: "كفر", translit: "Kufr", meaning: "disbelief", type: "noun", tajweed: "" },
    { arabic: "شرك", translit: "Shirk", meaning: "association", type: "noun", tajweed: "" },
    { arabic: "توحيد", translit: "Tawḥīd", meaning: "monotheism", type: "noun", tajweed: "ḥ" },
    { arabic: "إسلام", translit: "Islām", meaning: "submission", type: "noun", tajweed: "" },
    { arabic: "دين", translit: "Dīn", meaning: "religion", type: "noun", tajweed: "" },
    { arabic: "سنة", translit: "Sunnah", meaning: "tradition", type: "noun", tajweed: "" },
    { arabic: "فرض", translit: "Farḍ", meaning: "obligation", type: "noun", tajweed: "ḍ" },
    { arabic: "واجب", translit: "Wājib", meaning: "duty", type: "noun", tajweed: "" },
    { arabic: "حرام", translit: "Ḥarām", meaning: "forbidden", type: "noun", tajweed: "ḥ" },
    { arabic: "حلال", translit: "Ḥalāl", meaning: "permissible", type: "noun", tajweed: "ḥ" },
    { arabic: "صلاة", translit: "Ṣalāh", meaning: "prayer", type: "noun", tajweed: "ṣ" },
    { arabic: "زكاة", translit: "Zakāh", meaning: "charity", type: "noun", tajweed: "" },
    { arabic: "صوم", translit: "Ṣawm", meaning: "fasting", type: "noun", tajweed: "ṣ" },
    { arabic: "حج", translit: "Ḥajj", meaning: "pilgrimage", type: "noun", tajweed: "ḥ" },
    { arabic: "عمرة", translit: "'Umrah", meaning: "minor pilgrimage", type: "noun", tajweed: "‘ayn" },
    { arabic: "جهاد", translit: "Jihād", meaning: "struggle", type: "noun", tajweed: "" },
    { arabic: "دعاء", translit: "Du'ā'", meaning: "supplication", type: "noun", tajweed: "‘ayn" },
    { arabic: "ذكر", translit: "Dhikr", meaning: "remembrance", type: "noun", tajweed: "dh" },
    { arabic: "تسبيح", translit: "Tasbīḥ", meaning: "glorification", type: "noun", tajweed: "ḥ" },
    { arabic: "تحميد", translit: "Taḥmīd", meaning: "praise", type: "noun", tajweed: "ḥ" },
    { arabic: "تكبير", translit: "Takbīr", meaning: "magnification", type: "noun", tajweed: "" },
    { arabic: "تهليل", translit: "Tahlīl", meaning: "declaration of oneness", type: "noun", tajweed: "" },
    { arabic: "استغفار", translit: "Istighfār", meaning: "seeking forgiveness", type: "noun", tajweed: "gh" },
    { arabic: "توبة", translit: "Tawbah", meaning: "repentance", type: "noun", tajweed: "" },
    { arabic: "رحمة", translit: "Raḥmah", meaning: "mercy", type: "noun", tajweed: "ḥ" },
    { arabic: "مغفرة", translit: "Maghfirah", meaning: "forgiveness", type: "noun", tajweed: "gh" },
    { arabic: "عذاب", translit: "'Adhāb", meaning: "punishment", type: "noun", tajweed: "‘ayn, dh" },
    { arabic: "ثواب", translit: "Thawāb", meaning: "reward", type: "noun", tajweed: "th" },
    { arabic: "أجر", translit: "Ajr", meaning: "reward", type: "noun", tajweed: "" },
    { arabic: "سيئة", translit: "Sayyi'ah", meaning: "bad deed", type: "noun", tajweed: "" },
    { arabic: "حسنة", translit: "Ḥasanah", meaning: "good deed", type: "noun", tajweed: "ḥ" },
    { arabic: "ذنب", translit: "Dhanb", meaning: "sin", type: "noun", tajweed: "dh" },
    { arabic: "خطيئة", translit: "Khaṭī'ah", meaning: "mistake / sin", type: "noun", tajweed: "kh, ṭ" },
    { arabic: "إثم", translit: "Ithm", meaning: "sin", type: "noun", tajweed: "th" },
    { arabic: "بر", translit: "Birr", meaning: "righteousness", type: "noun", tajweed: "" },
    { arabic: "فجور", translit: "Fujūr", meaning: "wickedness", type: "noun", tajweed: "" },
    { arabic: "تقوى", translit: "Taqwā", meaning: "piety", type: "noun", tajweed: "q" },
    { arabic: "فسق", translit: "Fisq", meaning: "immorality", type: "noun", tajweed: "q" }
];

// ========== 200+ ISLAMIC PHRASES ==========
const phrasesData = [
    { arabic: "بسم الله", translit: "Bismillāh", meaning: "In the name of Allah", usage: "Before any action" },
    { arabic: "بسم الله الرحمن الرحيم", translit: "Bismillāh ir-Raḥmān ir-Raḥīm", meaning: "In the name of Allah, Most Gracious, Most Merciful", usage: "Before Quran recitation" },
    { arabic: "الحمد لله", translit: "Alḥamdulillāh", meaning: "All praise is to Allah", usage: "After completion, gratitude" },
    { arabic: "سبحان الله", translit: "SubḥānAllāh", meaning: "Glory be to Allah", usage: "Expressing wonder" },
    { arabic: "الله أكبر", translit: "Allāhu Akbar", meaning: "Allah is the Greatest", usage: "Expressing awe, takbir" },
    { arabic: "لا إله إلا الله", translit: "Lā ilāha illā Allāh", meaning: "There is no god but Allah", usage: "Shahada, dhikr" },
    { arabic: "محمد رسول الله", translit: "Muḥammadur Rasūlullāh", meaning: "Muhammad is the Messenger of Allah", usage: "Shahada" },
    { arabic: "أستغفر الله", translit: "Astaghfirullāh", meaning: "I seek forgiveness from Allah", usage: "After sin, dhikr" },
    { arabic: "ما شاء الله", translit: "Mā shā'a Allāh", meaning: "What Allah has willed", usage: "Expressing admiration" },
    { arabic: "إن شاء الله", translit: "In shā'a Allāh", meaning: "If Allah wills", usage: "For future plans" },
    { arabic: "جزاك الله خيرًا", translit: "Jazākallāhu khayrā", meaning: "May Allah reward you with goodness", usage: "Expressing thanks" },
    { arabic: "بارك الله فيك", translit: "Bārakallāhu fīk", meaning: "May Allah bless you", usage: "Showing appreciation" },
    { arabic: "السلام عليكم", translit: "As-salāmu 'alaykum", meaning: "Peace be upon you", usage: "Greeting" },
    { arabic: "وعليكم السلام", translit: "Wa 'alaykumus-salām", meaning: "And upon you be peace", usage: "Response to greeting" },
    { arabic: "الحمد لله رب العالمين", translit: "Alḥamdulillāhi rabbil 'ālamīn", meaning: "Praise be to Allah, Lord of the worlds", usage: "Surah Fatiha" },
    { arabic: "إنا لله وإنا إليه راجعون", translit: "Innā lillāhi wa innā ilayhi rāji'ūn", meaning: "To Allah we belong and to Him we return", usage: "At death or calamity" },
    { arabic: "حسبنا الله ونعم الوكيل", translit: "Ḥasbunallāhu wa ni'mal wakīl", meaning: "Sufficient for us is Allah, best disposer of affairs", usage: "In difficulty" },
    { arabic: "توكلت على الله", translit: "Tawakkaltu 'alallāh", meaning: "I put my trust in Allah", usage: "Starting a task" },
    { arabic: "لا حول ولا قوة إلا بالله", translit: "Lā ḥawla wa lā quwwata illā billāh", meaning: "No power or strength except with Allah", usage: "In hardship" },
    { arabic: "آمين", translit: "Āmīn", meaning: "O Allah, accept", usage: "End of dua" },
    { arabic: "صلى الله عليه وسلم", translit: "Ṣallallāhu 'alayhi wa sallam", meaning: "Peace and blessings be upon him", usage: "After Prophet's name" },
    { arabic: "عليه السلام", translit: "'Alayhis-salām", meaning: "Peace be upon him", usage: "After prophet's name" },
    { arabic: "رضي الله عنه", translit: "Raḍiyallāhu 'anh", meaning: "May Allah be pleased with him", usage: "After Sahabi name" },
    { arabic: "رحمه الله", translit: "Raḥimahullāh", meaning: "May Allah have mercy on him", usage: "After deceased scholar" },
    { arabic: "في سبيل الله", translit: "Fī sabīlillāh", meaning: "In the path of Allah", usage: "For Islamic cause" },
    { arabic: "الحمد لله على كل حال", translit: "Alḥamdulillāhi 'alā kulli ḥāl", meaning: "Praise be to Allah in every situation", usage: "After difficulty" },
    { arabic: "سبحان الله وبحمده", translit: "Subḥānallāhi wa biḥamdih", meaning: "Glory and praise be to Allah", usage: "Dhikr" },
    { arabic: "سبحان الله العظيم", translit: "Subḥānallāhil 'aẓīm", meaning: "Glory be to Allah, the Great", usage: "Dhikr" },
    { arabic: "لا إله إلا أنت سبحانك إني كنت من الظالمين", translit: "Lā ilāha illā anta subḥānaka innī kuntu minaẓ-ẓālimīn", meaning: "None has the right to be worshipped but You, Glory be to You, indeed I have been among the wrongdoers", usage: "Prophet Yunus's dua" },
    { arabic: "ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار", translit: "Rabbanā ātinā fid-dunyā ḥasanah wa fil-ākhirati ḥasanah wa qinā 'adhāban-nār", meaning: "Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire", usage: "Comprehensive dua" },
    { arabic: "رب زدني علما", translit: "Rabbi zidnī 'ilmā", meaning: "My Lord, increase me in knowledge", usage: "Seeking knowledge" },
    { arabic: "رب اغفر لي ولوالدي", translit: "Rabbighfirlī wa liwālidayya", meaning: "My Lord, forgive me and my parents", usage: "For parents" },
    { arabic: "ربنا تقبل منا", translit: "Rabbanā taqabbal minnā", meaning: "Our Lord, accept from us", usage: "After worship" },
    { arabic: "ربنا هب لنا من أزواجنا وذرياتنا قرة أعين", translit: "Rabbanā hab lanā min azwājinā wa dhurriyyātinā qurrata a'yun", meaning: "Our Lord, grant us from among our wives and offspring comfort to our eyes", usage: "For family" },
    { arabic: "ربنا لا تؤاخذنا إن نسينا أو أخطأنا", translit: "Rabbanā lā tu'ākhidhnā in nasīnā aw akhṭa'nā", meaning: "Our Lord, do not impose blame upon us if we forget or make a mistake", usage: "Seeking forgiveness" },
    
    // Prayer-Related Phrases
    { arabic: "أذان", translit: "Adhān", meaning: "Call to prayer", usage: "Prayer time" },
    { arabic: "إقامة", translit: "Iqāmah", meaning: "Second call to prayer", usage: "Before prayer starts" },
    { arabic: "قد قامت الصلاة", translit: "Qad qāmatis-ṣalāh", meaning: "Prayer has begun", usage: "In iqamah" },
    { arabic: "الله أكبر كبيرا", translit: "Allāhu akbar kabīrā", meaning: "Allah is the Greatest, abundantly great", usage: "Takbir at prayer start" },
    { arabic: "سبحانك اللهم وبحمدك", translit: "Subḥānakallāhumma wa biḥamdik", meaning: "Glory be to You, O Allah, and praise", usage: "Opening supplication" },
    { arabic: "أعوذ بالله من الشيطان الرجيم", translit: "A'ūdhu billāhi minash-shayṭānir-rajīm", meaning: "I seek refuge with Allah from the accursed Satan", usage: "Before reciting Quran" },
    { arabic: "اللهم إني أسألك الجنة", translit: "Allāhumma innī as'alukal-jannah", meaning: "O Allah, I ask You for Paradise", usage: "Dua" },
    { arabic: "اللهم إني أعوذ بك من النار", translit: "Allāhumma innī a'ūdhu bika minan-nār", meaning: "O Allah, I seek refuge with You from the Fire", usage: "Dua" },
    { arabic: "اللهم إني أعوذ بك من عذاب القبر", translit: "Allāhumma innī a'ūdhu bika min 'adhābil-qabr", meaning: "O Allah, I seek refuge with You from the punishment of the grave", usage: "Dua" },
    { arabic: "اللهم صل على محمد", translit: "Allāhumma ṣalli 'alā Muḥammad", meaning: "O Allah, send blessings upon Muhammad", usage: "Sending salawat" },
    { arabic: "ربنا ولك الحمد", translit: "Rabbanā wa lakal-ḥamd", meaning: "Our Lord, and to You is all praise", usage: "After rising from ruku" },
    { arabic: "سمع الله لمن حمده", translit: "Sami'allāhu liman ḥamidah", meaning: "Allah hears those who praise Him", usage: "When rising from ruku" },
    { arabic: "رب اغفر لي", translit: "Rabbighfirlī", meaning: "My Lord, forgive me", usage: "Between prostrations" },
    { arabic: "سبحان ربي العظيم", translit: "Subḥāna rabbiyal-'aẓīm", meaning: "Glory be to my Lord, the Great", usage: "In ruku" },
    { arabic: "سبحان ربي الأعلى", translit: "Subḥāna rabbiyal-a'lā", meaning: "Glory be to my Lord, the Most High", usage: "In sujood" },
    
    // Morning & Evening Phrases
    { arabic: "اللهم بك أصبحنا وبك أمسينا", translit: "Allāhumma bika aṣbaḥnā wa bika amsaynā", meaning: "O Allah, by You we enter the morning and by You we enter the evening", usage: "Morning/evening" },
    { arabic: "اللهم بك نحيا وبك نموت وإليك النشور", translit: "Allāhumma bika naḥyā wa bika namūtu wa ilaykan-nushūr", meaning: "O Allah, by You we live and by You we die, and to You is the resurrection", usage: "Morning/evening" },
    { arabic: "رضيت بالله ربا وبالإسلام دينا وبمحمد نبيا", translit: "Raḍītu billāhi rabban wa bil-islāmi dīnan wa bi-muḥammadin nabiyyā", meaning: "I am pleased with Allah as Lord, Islam as religion, and Muhammad as Prophet", usage: "Morning/evening" },
    
    // Protection Phrases
    { arabic: "بسم الله الذي لا يضر مع اسمه شيء", translit: "Bismillāh alladhī lā yaḍurru ma'asmihī shay'un", meaning: "In the name of Allah, with whose name nothing can cause harm", usage: "Protection" },
    { arabic: "أعوذ بكلمات الله التامات من شر ما خلق", translit: "A'ūdhu bikalimātillāhit-tāmmāti min sharri mā khalaq", meaning: "I seek refuge in the perfect words of Allah from the evil of what He has created", usage: "Protection" },
    { arabic: "حسبي الله لا إله إلا هو عليه توكلت", translit: "Ḥasbiyallāhu lā ilāha illā huwa 'alayhi tawakkaltu", meaning: "Allah is sufficient for me; none has the right to be worshipped but Him; upon Him I rely", usage: "When facing difficulty" }
];

// ========== KHUTBAH WORDS ==========
const khutbahWords = [
    { arabic: "تقوى", translit: "Taqwā", meaning: "consciousness of Allah" },
    { arabic: "صبر", translit: "Ṣabr", meaning: "patience" },
    { arabic: "توبة", translit: "Tawbah", meaning: "repentance" },
    { arabic: "استغفار", translit: "Istighfār", meaning: "seeking forgiveness" },
    { arabic: "جنة", translit: "Jannah", meaning: "paradise" },
    { arabic: "نار", translit: "Nār", meaning: "hellfire" },
    { arabic: "رحمة", translit: "Raḥmah", meaning: "mercy" },
    { arabic: "مغفرة", translit: "Maghfirah", meaning: "forgiveness" },
    { arabic: "هداية", translit: "Hidāyah", meaning: "guidance" },
    { arabic: "ضلال", translit: "Ḍalāl", meaning: "misguidance" },
    { arabic: "فتنة", translit: "Fitnah", meaning: "trial" },
    { arabic: "بلاء", translit: "Balā'", meaning: "test" },
    { arabic: "نعمة", translit: "Ni'mah", meaning: "blessing" },
    { arabic: "شكر", translit: "Shukr", meaning: "gratitude" },
    { arabic: "كفر", translit: "Kufr", meaning: "ingratitude / disbelief" },
    { arabic: "إيمان", translit: "Īmān", meaning: "faith" },
    { arabic: "إحسان", translit: "Iḥsān", meaning: "excellence" },
    { arabic: "إخلاص", translit: "Ikhlāṣ", meaning: "sincerity" },
    { arabic: "رياء", translit: "Riyā'", meaning: "show-off" },
    { arabic: "دنيا", translit: "Dunyā", meaning: "world" },
    { arabic: "آخرة", translit: "Ākhirah", meaning: "hereafter" },
    { arabic: "موت", translit: "Mawt", meaning: "death" },
    { arabic: "حياة", translit: "Ḥayāh", meaning: "life" },
    { arabic: "قبر", translit: "Qabr", meaning: "grave" },
    { arabic: "بعث", translit: "Ba'th", meaning: "resurrection" },
    { arabic: "حشر", translit: "Ḥashr", meaning: "gathering" },
    { arabic: "حساب", translit: "Ḥisāb", meaning: "accounting" },
    { arabic: "ميزان", translit: "Mīzān", meaning: "scale" },
    { arabic: "صراط", translit: "Ṣirāṭ", meaning: "path" },
    { arabic: "جسر", translit: "Jisr", meaning: "bridge" }
];

// ========== DHIKR SLIDES ==========
const dhikrSlides = [
    { arabic: "سُبْحَانَ اللَّهِ", translit: "SubḥānAllāh", meaning: "Glory be to Allah", count: 33 },
    { arabic: "الْحَمْدُ لِلَّهِ", translit: "Alḥamdulillāh", meaning: "All praise is due to Allah", count: 33 },
    { arabic: "اللَّهُ أَكْبَرُ", translit: "Allāhu Akbar", meaning: "Allah is the Greatest", count: 34 },
    { arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ", translit: "Lā ilāha illā Allāh", meaning: "There is no god but Allah", count: 100 },
    { arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", translit: "SubḥānAllāhi wa biḥamdih", meaning: "Glory and praise be to Allah", count: 100 },
    { arabic: "أَسْتَغْفِرُ اللَّهَ", translit: "Astaghfirullāh", meaning: "I seek forgiveness from Allah", count: 100 },
    { arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ", translit: "Allāhumma ṣalli 'alā Muḥammad", meaning: "O Allah, send blessings upon Muhammad", count: 100 },
    { arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", translit: "Lā ḥawla wa lā quwwata illā billāh", meaning: "No power nor strength except with Allah", count: 100 },
    { arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ", translit: "SubḥānAllāhi wa biḥamdih subḥānAllāhil-'aẓīm", meaning: "Glory and praise be to Allah, Glory be to Allah the Great", count: 100 },
    { arabic: "رَبِّ اغْفِرْ لِي وَارْحَمْنِي", translit: "Rabbighfirlī warḥamnī", meaning: "My Lord, forgive me and have mercy on me", count: 100 },
    { arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ", translit: "Allāhumma innī as'alukal-jannah", meaning: "O Allah, I ask You for Paradise", count: 100 },
    { arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ النَّارِ", translit: "Allāhumma innī a'ūdhu bika minan-nār", meaning: "O Allah, I seek refuge with You from the Fire", count: 100 },
    { arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً", translit: "Rabbanā ātinā fid-dunyā ḥasanah", meaning: "Our Lord, give us good in this world", count: 100 },
    { arabic: "رَبِّ زِدْنِي عِلْمًا", translit: "Rabbi zidnī 'ilmā", meaning: "My Lord, increase me in knowledge", count: 100 },
    { arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", translit: "Ḥasbunallāhu wa ni'mal wakīl", meaning: "Sufficient for us is Allah, and He is the best disposer of affairs", count: 100 },
    { arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ", translit: "Allāhumma anta rabbī lā ilāha illā anta", meaning: "O Allah, You are my Lord, none has the right to be worshipped but You", count: 1 },
    { arabic: "رَضِيتُ بِاللَّهِ رَبًّا", translit: "Raḍītu billāhi rabbā", meaning: "I am pleased with Allah as Lord", count: 3 },
    { arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ", translit: "Allāhumma innī as'alukal-'afwa wal-'āfiyah", meaning: "O Allah, I ask You for pardon and well-being", count: 3 },
    { arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى", translit: "Allāhumma innī as'alukal-hudā wat-tuqā", meaning: "O Allah, I ask You for guidance and piety", count: 3 },
    { arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَمَا قَرَّبَ إِلَيْهَا", translit: "Allāhumma innī as'alukal-jannata wa mā qarraba ilayhā", meaning: "O Allah, I ask You for Paradise and whatever brings me closer to it", count: 3 }
];

// ===== CRITICAL: Make all data available globally =====
window.arabicWords = arabicWords;
window.phrasesData = phrasesData;
window.khutbahWords = khutbahWords;
window.dhikrSlides = dhikrSlides;

// Log confirmation
console.log('✅ Arabic data loaded:', {
    words: arabicWords.length,
    phrases: phrasesData.length,
    khutbah: khutbahWords.length,
    slides: dhikrSlides.length
});